=== sunzidanasrin/Advance-Java/AdvanceJava/src/XML/src/xml/StudentList.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/StudentList.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE Students SYSTEM "StudentList.dtd">

    <Students>
    ...
    </Students>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Students (Student)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Student (Id|name|Age|Email)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Id (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT name (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Age (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Email (#PCDATA)>

=== sunzidanasrin/Advance-Java/AdvanceJava/src/XML/src/xml/StudentList.xml
<?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE Students SYSTEM "StudentList.dtd">
<Students>

    <Student>
        <Id>10236</Id>
        <name>Ruhul</name>
        <Age>22</Age>
        <Email>Ruhul@gmail.com</Email>
    </Student>

    <Student>
        <Id>10011</Id>
        <name>Shamim</name>
        <Age>21</Age>
        <Email>Shamim@gmail.com</Email>
    </Student>

</Students>
